/*
 * Copyright (c) 2025 Petr Miroslav Stepanek <petrstepanek99@gmail.com>
 *
 * This source code is licensed under a Dual License:
 * - AGPL-3.0 for open source use (see LICENSE file)
 * - Commercial License for business use (contact: petrstepanek99@gmail.com)
 *
 * This software contains patent-pending innovations in database analysis
 * and graph visualization. Commercial use requires separate licensing.
 */

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Config struct {
	Neo4j *Neo4jConfig `json:"neo4j"`
}

type Graph struct {
	Nodes         []*Node         `json:"nodes"`
	Relationships []*Relationship `json:"relationships"`
}

type Mutation struct {
}

type Neo4jConfig struct {
	URI      string `json:"uri"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Node struct {
	ID         string `json:"id"`
	Label      string `json:"label"`
	Properties string `json:"properties"`
}

type Query struct {
}

type Relationship struct {
	From       string `json:"from"`
	To         string `json:"to"`
	Type       string `json:"type"`
	Properties string `json:"properties"`
}

type Subscription struct {
}
