# GitHub Sponsors funding options

# GitHub Sponsors (preferred)
github: peter7775

# Ko-fi
ko_fi: # your-username

# Patreon
patreon: # your-username

# Open Collective
open_collective: # your-project

# Buy Me A Coffee
custom: ['https://www.buymeacoffee.com/yourname']

# PayPal
# paypal: # your-paypal-username

# Bitcoin
# bitcoin: # your-bitcoin-address

# Ethereum
# ethereum: # your-ethereum-address

# Custom funding URLs
# custom: ['https://example.com/sponsor', 'https://example.com/donate']
