run:
  timeout: 10m
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*/generated/.*"

linters-settings:
  lll:
    line-length: 120

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude mock and test specific issues
    - path: _test\.go
      linters:
        - typecheck
        - deadcode
        - unused
        - structcheck
        - varcheck
