---
services:

  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: testdata
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"
    volumes:
      - ./testdata/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptestpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  neo4j-test:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: neo4j/testpass
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_security_http_access_control_allow_origin: "*"
    ports:
      - "7687:7687"
      - "7474:7474"
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "testpass", "RETURN 1;"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

