---
services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: testdata
    ports:
      - "3307:3306"
    volumes:
      - ./testdata/mysql/:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--no-beep",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ptestpass",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  neo4j-test:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: neo4j/testpass
      NEO4J_dbms_security_auth__enabled: "true"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"
      NEO4J_dbms_connector_http_advertised__address: "localhost:7474"
      NEO4J_dbms_security_http_access_control_allow_origin: "*"
      NEO4J_dbms_connector_bolt_enabled: "true"
      NEO4J_dbms_connector_bolt_listen__address: "0.0.0.0:7687"
      NEO4J_dbms_connector_bolt_tls__level: "OPTIONAL"
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./testdata/neo4j/import:/import
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "testpass", "RETURN 1;"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      mysql-test:
        condition: service_healthy
    networks:
      - default
    environment:
      MYSQL_HOST: mysql-test
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: testdata
      NEO4J_URI: bolt://neo4j-test:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: testpass
    volumes:
      - .:/go/src/sql-graph-visualizer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: "no"

