FROM golang:1.22

ENV GO111MODULE=on
ENV GOPATH=/go
ENV PATH=$GOPATH/bin:$PATH

WORKDIR /go/src/github.com/peter7775/alevisualizer

# Kopírování go.mod a go.sum
COPY go.mod go.sum ./
RUN go mod download

# Kopírování zdrojového kódu
COPY . .

# Spuštění testů
CMD ["go", "test", "./...", "-v"] 