name: 🚀 Performance Issue
description: Report performance problems or slow operations
title: "[PERFORMANCE] "
labels: ["performance", "bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve performance!
        
  - type: textarea
    id: performance-issue
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem you're experiencing
      placeholder: The transformation is taking too long when...
    validations:
      required: true
      
  - type: dropdown
    id: operation-type
    attributes:
      label: Operation Type
      description: Which operation is slow?
      options:
        - Database Connection
        - SQL Data Extraction
        - Graph Transformation
        - Neo4j Data Loading
        - Visualization Rendering
        - API Response Time
        - Benchmark Execution
        - Full Pipeline
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: dataset-size
    attributes:
      label: Dataset Information
      description: Information about your dataset size and complexity
      placeholder: |
        - Number of tables: 50
        - Average table size: 10,000 rows
        - Number of relationships: 25
        - Database size: 2GB
    validations:
      required: true

  - type: textarea
    id: performance-metrics
    attributes:
      label: Current Performance
      description: What performance are you seeing?
      placeholder: |
        - Transformation time: 15 minutes
        - Memory usage: 4GB
        - CPU usage: 100%
        - Expected time: 2-3 minutes
    validations:
      required: true

  - type: textarea
    id: configuration-perf
    attributes:
      label: Configuration
      description: Share your configuration (especially connection pool settings)
      render: yaml
      placeholder: |
        mysql:
          max_open_conns: 25
          max_idle_conns: 5
          conn_max_lifetime: 5m
        # ... rest of config
    validations:
      required: true

  - type: textarea
    id: system-specs
    attributes:
      label: System Specifications
      description: Hardware and system information
      value: |
          - OS:
          - CPU:
          - RAM:
          - Storage Type:
          - Database Location: (local/remote/cloud)
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs-perf
    attributes:
      label: Performance Logs
      description: Any relevant logs or profiling data
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: tried-solutions
    attributes:
      label: Solutions Tried
      description: What have you already tried?
      options:
        - label: Adjusted connection pool settings
        - label: Increased system resources
        - label: Used batch processing
        - label: Optimized SQL queries
        - label: Checked database indexes
        - label: Monitored system resources

  - type: checkboxes
    id: terms-perf
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/peter7775/sql-graph-visualizer/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
