/*
 * Copyright (c) 2025 Petr Miroslav Stepanek <petrstepanek99@gmail.com>
 *
 * This source code is licensed under a Dual License:
 * - AGPL-3.0 for open source use (see LICENSE file)
 * - Commercial License for business use (contact: petrstepanek99@gmail.com)
 *
 * This software contains patent-pending innovations in database analysis
 * and graph visualization. Commercial use requires separate licensing.
 */

package models

import (
	"fmt"
	"strings"
)

// DatabaseType represents supported database types
type DatabaseType string

const (
	// DatabaseTypeMySQL represents MySQL database type
	DatabaseTypeMySQL DatabaseType = "mysql"
	// DatabaseTypePostgreSQL represents PostgreSQL database type
	DatabaseTypePostgreSQL DatabaseType = "postgresql"
	DatabaseTypeOracle     DatabaseType = "oracle"
)

// DatabaseSelector represents configuration for choosing database type
type DatabaseSelector struct {
	Type         DatabaseType      `yaml:"type"` // "mysql" or "postgresql"
	MySQL        *MySQLConfig      `yaml:"mysql,omitempty"`
	PostgreSQL   *PostgreSQLConfig `yaml:"postgresql,omitempty"`
	OracleConfig *OracleConfig     `yaml:"oracle,omitempty"`
}

// DatabaseConfig represents database connection configuration
type DatabaseConfig struct {
	Type       DatabaseType      `yaml:"type" json:"type"`
	MySQL      *MySQLConfig      `yaml:"mysql,omitempty" json:"mysql,omitempty"`
	PostgreSQL *PostgreSQLConfig `yaml:"postgresql,omitempty" json:"postgresql,omitempty"`
	Oracle     *OracleConfig     `yaml:"oracle,omitempty" json:"oracle,omitempty"`
}

// PostgreSQLConfig represents PostgreSQL database configuration
type PostgreSQLConfig struct {
	Host               string                   `yaml:"host" json:"host"`
	Port               int                      `yaml:"port" json:"port"`
	User               string                   `yaml:"user" json:"user"`
	Username           string                   `yaml:"username,omitempty" json:"username,omitempty"`
	Password           string                   `yaml:"password" json:"password"`
	Database           string                   `yaml:"database" json:"database"`
	Schema             string                   `yaml:"schema,omitempty" json:"schema,omitempty"`
	ConnectionMode     ConnectionMode           `yaml:"connection_mode,omitempty" json:"connection_mode,omitempty"`
	DataFiltering      DataFilteringConfig      `yaml:"data_filtering,omitempty" json:"data_filtering,omitempty"`
	Security           SecurityConfig           `yaml:"security" json:"security"`
	SSLConfig          SSLConfig                `yaml:"ssl" json:"ssl"`
	AutoGeneratedRules AutoGeneratedRulesConfig `yaml:"auto_generated_rules,omitempty" json:"auto_generated_rules,omitempty"`
	SearchPath         []string                 `yaml:"search_path,omitempty" json:"search_path,omitempty"`
	ApplicationName    string                   `yaml:"application_name,omitempty" json:"application_name,omitempty"`
	StatementTimeout   int                      `yaml:"statement_timeout,omitempty" json:"statement_timeout,omitempty"`
}

// OracleConfig represents Oracle Database configuration
type OracleConfig struct {
	Host        string `yaml:"host" json:"host"`
	Port        int    `yaml:"port" json:"port"`
	ServiceName string `yaml:"service_name" json:"service_name"`
	SID         string `yaml:"sid" json:"sid"`
	DSN         string `yaml:"dsn" json:"dsn"`

	Username string `yaml:"username" json:"username"`
	Password string `yaml:"password" json:"password"`

	MaxOpenConns    int `yaml:"max_open_conns" json:"max_open_conns"`
	MaxIdleConns    int `yaml:"max_idle_conns" json:"max_idle_conns"`
	ConnMaxLifetime int `yaml:"conn_max_lifetime" json:"conn_max_lifetime"`

	ConnectionTimeout int `yaml:"connection_timeout" json:"connection_timeout"`
	QueryTimeout      int `yaml:"query_timeout" json:"query_timeout"`

	Timezone        string `yaml:"timezone" json:"timezone"`
	WalletLocation  string `yaml:"wallet_location" json:"wallet_location"`
	ApplicationName string `yaml:"application_name" json:"application_name"`

	Security SecurityConfig `yaml:"security" json:"security"`
}

// GetActiveConfig returns the active database configuration based on the selected type
func (ds *DatabaseSelector) GetActiveConfig() DatabaseConfig {
	switch ds.Type {
	case DatabaseTypeMySQL:
		if ds.MySQL != nil {
			return DatabaseConfig{
				Type:  DatabaseTypeMySQL,
				MySQL: ds.MySQL,
			}
		}
	case DatabaseTypePostgreSQL:
		if ds.PostgreSQL != nil {
			return DatabaseConfig{
				Type:       DatabaseTypePostgreSQL,
				PostgreSQL: ds.PostgreSQL,
			}
		}
	case DatabaseTypeOracle:
		if ds.OracleConfig != nil {
			return DatabaseConfig{
				Type:   DatabaseTypeOracle,
				Oracle: ds.OracleConfig,
			}
		}
	}

	// Return empty config if no valid configuration is found
	return DatabaseConfig{}
}

// BuildConnectionString creates Oracle connection string
func (c *OracleConfig) BuildConnectionString() string {
	// If DSN is provided, use it directly (TNS descriptor)
	if c.DSN != "" {
		return fmt.Sprintf("oracle://%s:%s@%s", c.Username, c.Password, c.DSN)
	}

	// Build connection string for simple connection
	var connParts []string

	// Use service name if provided, otherwise SID
	if c.ServiceName != "" {
		connParts = append(connParts, fmt.Sprintf("oracle://%s:%s@%s:%d/%s",
			c.Username, c.Password, c.Host, c.Port, c.ServiceName))
	} else if c.SID != "" {
		// For SID connections, use different format
		connParts = append(connParts, fmt.Sprintf("oracle://%s:%s@%s:%d/%s?SID=%s",
			c.Username, c.Password, c.Host, c.Port, c.SID, c.SID))
	} else {
		// Default to XE service
		connParts = append(connParts, fmt.Sprintf("oracle://%s:%s@%s:%d/XE",
			c.Username, c.Password, c.Host, c.Port))
	}

	connString := connParts[0]

	// Add additional parameters
	params := make([]string, 0)

	if c.ConnectionTimeout > 0 {
		params = append(params, fmt.Sprintf("TIMEOUT=%d", c.ConnectionTimeout))
	}

	if c.Timezone != "" {
		params = append(params, fmt.Sprintf("TIMEZONE=%s", c.Timezone))
	}

	if c.WalletLocation != "" {
		params = append(params, fmt.Sprintf("WALLET=%s", c.WalletLocation))
	}

	if len(params) > 0 {
		if strings.Contains(connString, "?") {
			connString += "&" + strings.Join(params, "&")
		} else {
			connString += "?" + strings.Join(params, "&")
		}
	}

	return connString
}

// Validate checks if Oracle configuration is valid
func (c *OracleConfig) Validate() error {
	if c.Username == "" {
		return fmt.Errorf("oracle username is required")
	}

	if c.Password == "" {
		return fmt.Errorf("oracle password is required")
	}

	// If DSN is not provided, check basic connection info
	if c.DSN == "" {
		if c.Host == "" {
			return fmt.Errorf("oracle host is required when DSN is not provided")
		}

		if c.Port <= 0 {
			c.Port = 1521 // Default Oracle port
		}

		if c.ServiceName == "" && c.SID == "" {
			c.ServiceName = "XE" // Default to Oracle XE
		}
	}

	// Set defaults
	if c.MaxOpenConns <= 0 {
		c.MaxOpenConns = 10
	}

	if c.MaxIdleConns <= 0 {
		c.MaxIdleConns = 5
	}

	if c.ConnectionTimeout <= 0 {
		c.ConnectionTimeout = 30
	}

	if c.QueryTimeout <= 0 {
		c.QueryTimeout = 30
	}

	if c.ApplicationName == "" {
		c.ApplicationName = "sql-graph-visualizer"
	}

	// Set security defaults
	if c.Security.MaxConnections <= 0 {
		c.Security.MaxConnections = c.MaxOpenConns
	}

	if c.Security.ConnectionTimeout <= 0 {
		c.Security.ConnectionTimeout = c.ConnectionTimeout
	}

	if c.Security.QueryTimeout <= 0 {
		c.Security.QueryTimeout = c.QueryTimeout
	}

	return nil
}

// GetDatabaseType returns the database type.
func (d *DatabaseConfig) GetDatabaseType() DatabaseType {
	return d.Type
}

// GetHost returns the host from the active database config.
func (d *DatabaseConfig) GetHost() string {
	switch d.Type {
	case DatabaseTypeMySQL:
		if d.MySQL != nil {
			return d.MySQL.Host
		}
	case DatabaseTypePostgreSQL:
		if d.PostgreSQL != nil {
			return d.PostgreSQL.Host
		}
	case DatabaseTypeOracle:
		if d.Oracle != nil {
			return d.Oracle.Host
		}
	}
	return ""
}

// GetPort returns the port from the active database config.
func (d *DatabaseConfig) GetPort() int {
	switch d.Type {
	case DatabaseTypeMySQL:
		if d.MySQL != nil {
			return d.MySQL.Port
		}
	case DatabaseTypePostgreSQL:
		if d.PostgreSQL != nil {
			return d.PostgreSQL.Port
		}
	case DatabaseTypeOracle:
		if d.Oracle != nil {
			return d.Oracle.Port
		}
	}
	return 0
}

// GetUsername returns the username from the active database config.
func (d *DatabaseConfig) GetUsername() string {
	switch d.Type {
	case DatabaseTypeMySQL:
		if d.MySQL != nil {
			return d.MySQL.GetUsername()
		}
	case DatabaseTypePostgreSQL:
		if d.PostgreSQL != nil {
			return d.PostgreSQL.GetUsername()
		}
	case DatabaseTypeOracle:
		if d.Oracle != nil {
			return d.Oracle.Username
		}
	}
	return ""
}

// GetDataFiltering returns the data filtering config from the active database config.
func (d *DatabaseConfig) GetDataFiltering() DataFilteringConfig {
	switch d.Type {
	case DatabaseTypeMySQL:
		if d.MySQL != nil {
			return d.MySQL.DataFiltering
		}
	case DatabaseTypePostgreSQL:
		if d.PostgreSQL != nil {
			return d.PostgreSQL.DataFiltering
		}
	}
	return DataFilteringConfig{}
}

// GetEffectiveConfig returns the active database config based on type
func (d *DatabaseConfig) GetEffectiveConfig() interface{} {
	switch d.Type {
	case DatabaseTypeMySQL:
		return d.MySQL
	case DatabaseTypePostgreSQL:
		return d.PostgreSQL
	case DatabaseTypeOracle:
		return d.Oracle
	default:
		return nil
	}
}

// Validate validates the database configuration
func (d *DatabaseConfig) Validate() error {
	switch d.Type {
	case DatabaseTypeMySQL:
		if d.MySQL == nil {
			return fmt.Errorf("mysql configuration is required when type is mysql")
		}
		// Add MySQL-specific validation if needed
	case DatabaseTypePostgreSQL:
		if d.PostgreSQL == nil {
			return fmt.Errorf("postgresql configuration is required when type is postgresql")
		}
		// Add PostgreSQL-specific validation if needed
	case DatabaseTypeOracle:
		if d.Oracle == nil {
			return fmt.Errorf("oracle configuration is required when type is oracle")
		}
		return d.Oracle.Validate()
	default:
		return fmt.Errorf("unsupported database type: %s", d.Type)
	}
	return nil
}

// IsSupported checks if the database type is supported
func (dt DatabaseType) IsSupported() bool {
	switch dt {
	case DatabaseTypeMySQL, DatabaseTypePostgreSQL, DatabaseTypeOracle:
		return true
	default:
		return false
	}
}

// Validate validates the database selector configuration.
func (ds *DatabaseSelector) Validate() error {
	if ds.Type == "" {
		return fmt.Errorf("database.type: Database type must be specified")
	}
	return nil
}

// String returns string representation of database type
func (dt DatabaseType) String() string {
	return string(dt)
}
