package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	graphql1 "mysql-graph-visualizer/internal/application/services/graphql/generated"
	"mysql-graph-visualizer/internal/domain/aggregates/graph"
	graphqlModels "mysql-graph-visualizer/internal/domain/models/graphql"
)

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context) ([]*graphqlModels.Node, error) {
	graphAgg := graph.NewGraphAggregate("")
	nodes := graphAgg.GetNodes()

	var gqlNodes []*graphqlModels.Node
	for _, node := range nodes {
		var props *graphqlModels.Properties
		if node.Properties != nil {
			key, keyOk := node.Properties["key"].(string)
			value, valueOk := node.Properties["value"].(string)
			if keyOk && valueOk {
				props = &graphqlModels.Properties{
					Key:   &key,
					Value: &value,
				}
			}
		}

		gqlNode := &graphqlModels.Node{
			ID:         node.ID,
			Label:      node.Type,
			Properties: props,
		}
		gqlNodes = append(gqlNodes, gqlNode)
	}

	return gqlNodes, nil
}

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
