/*
 * Copyright (c) 2025 Petr Miroslav Stepanek <petrstepanek99@gmail.com>
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	graphql "mysql-graph-visualizer/internal/application/services/graphql/generated"
	graphqlModels "mysql-graph-visualizer/internal/domain/models/graphql"
)

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context) ([]*graphqlModels.Node, error) {
	graphAgg := graph.NewGraphAggregate("")
	nodes := graphAgg.GetNodes()

	var gqlNodes []*graphqlModels.Node
	for _, node := range nodes {
		var props *graphqlModels.Properties
		if node.Properties != nil {
			props = &graphqlModels.Properties{
				Key:   node.Properties["key"].(string),
				Value: node.Properties["value"].(string),
			}
		}

		gqlNode := &graphqlModels.Node{
			ID:         node.ID,
			Label:      node.Type,
			Properties: props,
		}
		gqlNodes = append(gqlNodes, gqlNode)
	}

	return gqlNodes, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graphql.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
