# SQL Graph Visualizer - Cloud Deployment Configuration
# This configuration uses environment variables for sensitive data

# Server Configuration
server:
  port: ${PORT:-3000}
  api_port: ${API_PORT:-8080}
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

# MySQL Database (Railway managed)
mysql:
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT:-3306}
  user: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  database: ${MYSQL_DATABASE}
  max_open_conns: 20
  max_idle_conns: 5
  conn_max_lifetime: 5m
  conn_max_idle_time: 10m
  timeout: 10s
  charset: utf8mb4

# Neo4j AuraDB (Cloud managed)
neo4j:
  uri: ${NEO4J_URI}
  user: ${NEO4J_USER:-neo4j}
  password: ${NEO4J_PASSWORD}
  max_connection_pool_size: 50
  connection_timeout: 10s
  max_transaction_retry_time: 15s

# Demo settings
demo:
  enabled: ${DEMO_MODE:-true}
  auto_transform_on_start: ${AUTO_TRANSFORM:-true}
  sample_data_loaded: false
  reset_on_restart: false
  show_demo_banner: true
  demo_scenario: "cloud_demo"

# Performance Benchmarking (disabled for cloud demo)
benchmark:
  enabled: false

# Simple transformation rules for cloud demo
transform_rules:
  # Basic users transformation
  - name: "users_to_graph"
    rule_type: "node"
    source:
      type: "query"
      value: "SELECT id, username, email, created_at FROM users LIMIT 100"
    target_type: "User"
    field_mappings:
      id: "user_id"
      username: "username"
      email: "email"
      created_at: "registration_date"

# Processing Configuration (optimized for cloud)
processing:
  batch_size: 500
  max_memory_mb: 512
  parallel_workers: 2
  transaction_size: 100

# Logging (cloud-friendly)
logging:
  level: ${LOG_LEVEL:-info}
  format: json
  output: stdout
  enable_performance_logs: false
  log_slow_queries: false

# API Configuration (open for demo)
api:
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "OPTIONS"]
    allowed_headers: ["*"]
    max_age: 3600
  
  rate_limit:
    enabled: true
    requests_per_minute: 60
    burst: 10

  graphql:
    playground_enabled: true
    introspection_enabled: true
    complexity_limit: 500

# Visualization Settings
visualization:
  node_colors:
    User: "#4CAF50"
    Product: "#2196F3" 
    Category: "#FF9800"
  
  relationship_colors:
    RELATED_TO: "#757575"
    BELONGS_TO: "#607D8B"

# Monitoring and Health Checks
monitoring:
  health_check:
    enabled: true
    endpoint: "/api/health"
    include_database_status: true
  
  metrics:
    enabled: false  # Disabled for demo

# Security (demo-friendly)
security:
  enable_auth: false
  cors_enabled: true
  rate_limiting_enabled: true
  input_validation_enabled: true

# Demo info
demo_info:
  description: "Cloud demo with minimal sample data"
  message: "This is a live demo running on Railway with Neo4j AuraDB"
  contact: "https://github.com/peter7775/sql-graph-visualizer"
