/*
 * Copyright (c) 2025 Petr Miroslav Stepanek <petrstepanek99@gmail.com>
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Node struct {
	ID         string      `json:"id"`
	Label      string      `json:"label"`
	Properties *Properties `json:"properties,omitempty"`
}

type Properties struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Query struct {
}
