// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Node struct {
	ID         string      `json:"id"`
	Label      string      `json:"label"`
	Properties *Properties `json:"properties,omitempty"`
}

type Properties struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Query struct {
}
